describe("clerkMiddleware", () => {
  describe("with handler and options", () => {
    it.todo("should assign auth to context");
  });

  describe("with options", () => {
    it.todo("should assign auth to context");
  });

  it.todo("should set http 307 redirect and headers for handshake");

  it.todo("should raise error for handshake case without location header");

  it.todo("should set headers to response generated by the clerk backend");

  it.todo("should assign auth to context");
});
